import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Layout from '../components/Layout.js'

export default function Page() {
  const [articles, setArticles] = useState([]) // Händer först

  useEffect(() => { 
    // Händer tvåa
    // React group function - hook? Is run after the page is ready (return delen)
    async function fetchData() {
      const response = await fetch('/api/articles')
      const articles = await response.json()
      setArticles(articles)
    }
    fetchData()
  }, [])
  return (
    // Händer trea
    <Layout>
      <Head>
        <title>WebTech - articles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        Web technologies articles
      </h1>
      <p className='italic hover:not-italic'>This page fetch data from the client side, not good for SEO.</p>
      <ul>
        {articles.map( article => (
          <li key={article.slug}>
            <h2><Link href={`/articles/${article.slug}`}>{article.title}</Link></h2>
            <p>{article.message}</p>
          </li>
        ))}
      </ul>
    </Layout>
  )
} // <p> {article1 && article1.title} </p>  Ser till att article1 är redo innan den laddas på sidan.
