import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header.js'
import Footer from './components/Footer.js'
import {Providers} from './providers.js'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
      <body>
      <Header />
        {children}
        <Footer />
      </body>
      </Providers>
     </html> 
  )
}
